import './globals.css'
import SceneProvider from '@/libs/three/components/SceneProvider'
import localFont from 'next/font/local'
import { Analytics } from "@vercel/analytics/react";

const satoshi = localFont({ src: '../@assets/fonts/Satoshi-Variable.woff2', display: 'swap' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='antialiased'>
      <body className={satoshi.className}>
        <SceneProvider>
          {children}
        </SceneProvider>
        <Analytics/>
      </body>
    </html>
  )
}
